#!/bin/sh

# PROVIDE: router
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="router"
desc="Multi-function routing daemon"

pidfile="/var/run/${name}.pid"
command=/usr/sbin/daemon
command_args="-r /bin/sh /usr/bin/router"

run_rc_command "$1"